import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Intro from '@/sections/Intro';

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-10">
        <Navbar />
        <Intro />
      </main>
    </>
  );
}
