import Head from 'next/head';
import Navbar from '@/components/Navbar';
import Intro from '@/sections/Intro';
import About from '@/sections/About';
import { useRef } from 'react';
import Experience from '@/sections/Experience';
import Work from '@/sections/Work';
import Contact from '@/sections/Contact';

export default function Home() {
  const aboutRef = useRef<HTMLDivElement>(null);
  const experienceRef = useRef<HTMLDivElement>(null);
  const workRef = useRef<HTMLDivElement>(null);
  const contactRef = useRef<HTMLDivElement>(null);

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-[10vw]">
        <header>
          <Navbar>
            <button
              className="hover:text-cyan-300 text-slate-300"
              onClick={() => aboutRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>
              About
            </button>
            <button
              className="hover:text-cyan-300 text-slate-300"
              onClick={() => experienceRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>
              Experience
            </button>
            <button
              className="hover:text-cyan-300 text-slate-300"
              onClick={() => workRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>
              Work
            </button>
            <button
              className="hover:text-cyan-300 text-slate-300"
              onClick={() => contactRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>
              Contact
            </button>
          </Navbar>
        </header>
        <Intro />
        <div ref={aboutRef} className="scroll-mt-20">
          <About />
        </div>
        <div ref={experienceRef} className="scroll-mt-20">
          <Experience />
        </div>
        <div ref={workRef} className="scroll-mt-20">
          <Work />
        </div>
        <div ref={contactRef} className="scroll-mt-20">
          <Contact />
        </div>
      </main>
    </>
  );
}
